Financeiro/FinanceiroWeb/Controllers/MovimentoController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceiroWeb.Controllers
{
    public class MovimentoController : PageBase
    {
        // GET: Movimento
        public void MontarTitulo(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    ViewBag.Titulo = "Novo Movimento";
                    ViewBag.SubTitulo = "Aqui você cadastra seus movimentos!";
                    break;

                

                case 2:
                    ViewBag.Titulo = "Consultar Movimento";
                    ViewBag.SubTitulo = "Aqui você consulta sesus movimentos!";
                    break;
            }
        }

        public ActionResult Nova()
        {
            CarregarConta();
            CarregarCategoria();
            CarregarEmpresa();
            MontarTitulo(1);

            return View();
        }

        public ActionResult Consultar()
        {
            MontarTitulo(2);
            return View();
        }

        public void CarregarConta()
        {
            ViewBag.listaContas = new ContaDAO().ListarConta(CodigoLogado);
        }
        public void CarregarCategoria()
        {
            ViewBag.listaCategorias = new CategoriaDAO().ConsultarCategoria(CodigoLogado);
        }
        public void CarregarEmpresa()
        {
            ViewBag.listaEmpresas = new EmpresaDAO().ConsultarEmpresa(CodigoLogado);
        }

        public ActionResult FiltrarMov(string tipo, string dtInicial, string dtFinal)
        {
            ViewBag.tipo_mov = tipo;
            ViewBag.DataInicial = dtInicial;
            ViewBag.DataFinal = dtFinal;

            if (tipo == "" || dtFinal == "" || dtInicial == "")
            {
                ViewBag.Validar = 0;
            }
            else
            {
                MovimentoDAO objdao = new MovimentoDAO();

                ViewBag.movimentos = objdao.ConsultarMovimento(CodigoLogado, Convert.ToInt16(tipo), Convert.ToDateTime(dtInicial), Convert.ToDateTime(dtFinal));

                
            }
            MontarTitulo(1);
            return View("Consultar");
        }
        public ActionResult Gravar(string tipo_mov, string data_mov, Decimal valor_mov, string obs_mov, string id_conta, string id_categoria, string id_empresa)
        {
            // string pagina = "";
            

            if (tipo_mov == "" || data_mov == "" || valor_mov == 0 || id_categoria == "" || id_conta == "" || id_empresa == "")
                {
                    ViewBag.Validar = 0;
                }
                else
                {
                    tb_movimento objMov = new tb_movimento();
                    MovimentoDAO objdao = new MovimentoDAO();

                    objMov.id_usuario = CodigoLogado;
                    objMov.data_movimento = Convert.ToDateTime(data_mov);
                    objMov.valor_movimento = valor_mov;
                    objMov.obs_movimento = obs_mov;
                    objMov.tipo_movimento = Convert.ToInt16(tipo_mov);
                    objMov.id_conta = Convert.ToInt32(id_conta);
                    objMov.id_empresa = Convert.ToInt32(id_empresa);
                    objMov.id_categoria = Convert.ToInt32(id_categoria);

                try
                    {
                        
                        objdao.SalvarMovimento(objMov);
                        
                        ViewBag.Validar = 1;
                    }
                    catch
                    {

                        ViewBag.Validar = -1;
                    }
                }

                MontarTitulo(2);
               // pagina = "Nova";

                CarregarConta();
                CarregarCategoria();
                CarregarEmpresa();

            return View("Nova");
        }

        
    }
}

Financeiro/FinanceiroWeb/Views/Movimento/Consultar.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}
@using (Html.BeginForm("FiltrarMov", "Movimento", FormMethod.Post))
{
    <!-- /. ROW  -->
    <hr />
    <div class="form-group">
        <label>Tipo de movimentação:</label>
        <select class="form-control" name="tipo">
            @{ string sel = "";}

            <option value="2" @{if (ViewBag.tipo_mov == "2") { sel = "selected"; } else { sel = ""; } } @sel>
                Todos
            </option>
            <option value="0" @{if (ViewBag.tipo_mov == "0") { sel = "selected"; } else { sel = ""; } } @sel>
                Entrada
            </option>
            <option value="1" @{if (ViewBag.tipo_mov == "1") { sel = "selected"; } else { sel = ""; } } @sel>
                Saída
            </option>
        </select>
        <br>
        <label>Data Inicial</label>
        <input type="date" class="form-control" name="dtInicial" value="@ViewBag.DataInicial" />
        <br>
        <label>Data Final</label>
        <input type="date" class="form-control" name="dtFinal" value="@ViewBag.DataFinal" />
        <br>
    </div>

    <button type="submit" class="btn btn-info" name="btnPesquisar">Pesquisar</button>
}
<!-- /. ROW  -->
<hr />
@{if (ViewBag.movimentos != null)
    {
        <div class="row">
            <div class="col-md-12">
                <!-- Advanced Tables -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Lista de Movimentos
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>Conta/Banco</th>
                                        <th>Empresa </th>
                                        <th>Categoria </th>
                                        <th>Data </th>
                                        <th>Valor</th>
                                        <th>Observação</th>

                                        <th>Ação</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in ViewBag.movimentos)
                                    {

                                        <tr class="odd gradeX">
                                            <td> @item.Tipo</td>
                                            <td> @item.Conta</td>
                                            <td> @item.Empresa</td>
                                            <td> @item.Categoria</td>
                                            <td> @item.Data</td>
                                            <td> @item.Valor</td>
                                            <td> @item.Observacao</td>

                                        </tr>
                                    }



                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                <!--End Advanced Tables -->
            </div>
        </div>
    }


}

Financeiro/FinanceiroWeb/Views/Movimento/Nova.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}
@using (Html.BeginForm("Gravar", "Movimento", FormMethod.Post))
{
    <div class="form-group">
        <div class="form-group">
            <label>Tipo de movimentação:</label>
            <select class="form-control" id="tipo_mov" name="tipo_mov">

                <option value="" selected>Selecione</option>
                <option value="0">Entreda</option>
                <option value="1">Saída</option>
            </select>
            <label id="val_tipo_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Data</label>
            <input type="date" class="form-control" id="data_mov" name="data_mov" />
            <label id="val_data_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Selecione a conta:</label>
            <select class="form-control" id="conta_mov" name="id_conta">
                <option value="" selected>Selecione</option>
                @foreach (var item in ViewBag.listaContas)
                {
                    <option value="@item.idConta">@item.Agencia</option>
                }
            </select>
            <label id="val_conta_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Selecione a empresa:</label>
            <select class="form-control" id="empresa_mov" name="id_empresa">

                <option value="" selected>Selecione</option>
                @foreach (var item in ViewBag.listaEmpresas)
                {
                    <option value="@item.id_empresa">@item.nome_empresa</option>
                }
            </select>
            <label id="val_empresa_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Selecione a categoria:</label>
            <select class="form-control" id="categoria_mov" name="id_categoria">
                <option value="" selected>Selecione</option>
                @foreach (var item in ViewBag.listaCategorias)
                {
                    <option value="@item.id_categoria">@item.nome_categoria</option>
                }
            </select>
            <label id="val_categoria_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Valor</label>
            <input type="text" class="form-control" id="valor_mov" name="valor_mov" />
            <label id="val_valor_mov" class="estilo-validar"></label>
        </div>
        <div class="form-group">
            <label>Observações</label>
            <textarea class="form-control" rows="3" name="obs_mov"></textarea>
        </div>
    </div>
    <button type="submit" class="btn btn-success" name="btnSalvar" onclick="return ValidarCampos(99)">Lançar</button>
}
