Financeiro/FinanceiroWeb/Controllers/BancoController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceiroWeb.Controllers
{
    public class BancoController : PageBase
    {
        // GET: Banco
        public void MontarTitulo(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    ViewBag.Titulo = "Novo Banco";
                    ViewBag.SubTitulo = "Aqui você cadastra suas bancos!";
                    break;

                case 2:
                    ViewBag.Titulo = "Alterar Banco";
                    ViewBag.SubTitulo = "Aqui você altera suas bancos!";
                    break;

                case 3:
                    ViewBag.Titulo = "Consultar Banco";
                    ViewBag.SubTitulo = "Aqui você consulta suas banco!";
                    break;
            }
        }
        private void CarregarBancos()
        {
            BancoDAO objDao = new BancoDAO();
            ViewBag.listaBanco = objDao.ConsultarBanco(CodigoLogado);
        }
        // GET: Empresa
        public ActionResult Nova()
        {

            MontarTitulo(1);

            return View();
        }
        public ActionResult Alterar(int cod, string codbanco, string nome)
        {
            ViewBag.cod = cod;
            ViewBag.codbanco = codbanco;
            ViewBag.nome = nome;

            MontarTitulo(2);

            return View();
        }

        public ActionResult Consultar()
        {
            CarregarBancos();
            MontarTitulo(3);

            return View();
        }
        public ActionResult Gravar(int? cod, string codigo_banco, string nome_banco, string btn)
        {
            string pagina = "";

            if (btn == "excluir")
            {
                BancoDAO objdao = new BancoDAO();
                try
                {
                    objdao.ExcluirBanco(Convert.ToInt32(cod));
                    ViewBag.Validar = 2;
                }
                catch
                {

                    ViewBag.Validar = -3;
                }
                finally
                {
                    MontarTitulo(3);
                    CarregarBancos();
                    pagina = "Consultar";
                }
            }
            else
            {
                if (nome_banco == "" || codigo_banco == "")
                {
                    ViewBag.Validar = 0;
                }
                else
                {
                    tb_banco objBanco = new tb_banco();
                    BancoDAO objdao = new BancoDAO();

                    objBanco.id_usuario = CodigoLogado;
                    objBanco.nome_banco = nome_banco.Trim();
                    objBanco.codigo_banco = codigo_banco.Trim();

                    try
                    {
                        if (cod == null)
                        {
                            objdao.SalvarBanco(objBanco);
                        }
                        else
                        {
                            objBanco.id_banco = Convert.ToInt32(cod);
                            objdao.AlterarBanco(objBanco);
                        }

                        ViewBag.Validar = 1;
                    }
                    catch
                    {

                        ViewBag.Validar = -1;
                    }
                }
                if (cod == null)
                {
                    MontarTitulo(1);
                    pagina = "Nova";
                }
                else
                {
                    ViewBag.cod = cod;
                    ViewBag.nome = nome_banco;
                    ViewBag.codbanco = codigo_banco;

                    MontarTitulo(2);
                    pagina = "Alterar";

                }
            }
            return View(pagina);
            
            //return cod == null ? View("Nova") : View("Alterar");
        }
    }
}

Financeiro/FinanceiroWeb/Views/Banco/Alterar.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}
@using (Html.BeginForm("Gravar", "Banco", FormMethod.Post))
{
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="form-group">
        <label>Código do banco</label>
        <input class="form-control" placeholder="Digite aqui.." id="codigo_banco" name="codigo_banco" value="@ViewBag.codbanco" />
        <label id="val_cod_banco" class="estilo-validar"></label>
        <br>
        <label>Nome do banco</label>
        <input class="form-control" placeholder="Digite aqui.." id="nome_banco" name="nome_banco" value="@ViewBag.nome" />
        <label id="val_nome_banco" class="estilo-validar"></label>
        <br>
    </div>
    <button type="submit" class="btn btn-success" onclick="return ValidarCampos(3)" name="btn" value="salvar">Salvar</button>
    <button type="submit" class="btn btn-danger" name="btn" value="excluir">Excluir</button>
}


Financeiro/FinanceiroWeb/Views/Banco/Consultar.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}


<!-- /. ROW  -->
<hr />
<div class="row">
    <div class="col-md-12">
        <!-- Advanced Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Lista de Bancos
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Código banco</th>
                                <th>Nome do banco </th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in ViewBag.listaBanco)
                            {
                            <tr class="odd gradeX">
                                <td> @item.codigo_banco</td>
                                <td> @item.nome_banco</td>
                                <td>
                                    <a href="/Banco/Alterar?cod=@item.id_banco&codbanco=@item.codigo_banco&nome=@item.nome_banco" class="btn btn-warning btn-xs">Alterar</a>
                                </td>
                            </tr>
                            }

                            <tr class="odd gradeX">
                                
                                <td>
                                    <a href="banco_alterar.php?cod=" class="btn btn-warning btn-xs">Alterar</a>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!--End Advanced Tables -->
    </div>
</div>


Financeiro/FinanceiroWeb/Views/Banco/Nova.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}
@using (Html.BeginForm("Gravar", "Banco", FormMethod.Post))
{
    <div class="form-group">
        <label>Código do banco</label>
        <input class="form-control" placeholder="Digite aqui.." id="codigo_banco" name="codigo_banco" />
        <label id="val_cod_banco" class="estilo-validar"></label>
        <br>
        <label>Nome do banco</label>
        <input class="form-control" placeholder="Digite aqui.." id="nome_banco" name="nome_banco" />
        <label id="val_nome_banco" class="estilo-validar"></label>
        <br>
    </div>
    <button type="submit" class="btn btn-success" name="btnSalvar" onclick="return ValidarCampos(3)">Salvar</button>

}
