Financeiro/FinanceiroWeb/Controllers/ContaController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceiroWeb.Controllers
{
    public class ContaController : PageBase
    {
        // GET: Conta
        public void MontarTitulo(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    ViewBag.Titulo = "Nova Conta";
                    ViewBag.SubTitulo = "Aqui você cadastra suas contas!";
                    break;

                case 2:
                    ViewBag.Titulo = "Alterar Conta";
                    ViewBag.SubTitulo = "Aqui você altera suas contas!";
                    break;

                case 3:
                    ViewBag.Titulo = "Consultar Conta";
                    ViewBag.SubTitulo = "Aqui você consulta suas conta!";
                    break;
            }
        }

        // GET: Empresa
        public ActionResult Nova()
        {
            CarregarBanco();
            MontarTitulo(1);

            return View();
        }
        public ActionResult Alterar(int cod, int banco, string agencia, string numero, string saldo, string status)
        {
            ViewBag.cod = cod;
            ViewBag.banco = banco;
            ViewBag.agencia = agencia;
            ViewBag.numero = numero;
            ViewBag.saldo = saldo;
            ViewBag.status = status;
            CarregarBanco();
            MontarTitulo(2);

            return View();
        }

        public ActionResult Consultar()
        {
            CarregarConta();
            CarregarBanco();
            MontarTitulo(3);

            return View();
        }

        public void CarregarConta()
        {
            ViewBag.listarContas = new ContaDAO().ListarConta(CodigoLogado);
        }
        private void CarregarBanco()
        {
            BancoDAO objDao = new BancoDAO();
            ViewBag.listaBancos = objDao.ConsultarBanco(CodigoLogado);
            //ViewBag.listaBancos = new BancoDAO().ConsultarBanco(CodigoLogado);
        }
        public ActionResult Gravar(int? cod, string agencia_conta, string numero_conta, Decimal saldo_conta, int id_banco, string status_conta, string btn)
        {
            string pagina = "";
            if (btn == "excluir")
            {
                ContaDAO objdao = new ContaDAO();
                try
                {
                    objdao.ExcluirConta(Convert.ToInt32(cod));
                    ViewBag.Validar = 2;
                }
                catch (Exception)
                {
                    ViewBag.Validar = -3;
                }
                finally
                {
                    MontarTitulo(3);
                    CarregarConta();
                    pagina = "Consultar";
                }
            }
            else
            {
                if (agencia_conta == "" || numero_conta == "" || saldo_conta == 0)
                {
                    ViewBag.Validar = 0;
                }
                else
                {
                    tb_conta objConta = new tb_conta();
                    ContaDAO objdao = new ContaDAO();

                    objConta.id_usuario = CodigoLogado;
                    objConta.agencia_conta = agencia_conta.Trim();
                    objConta.numero_conta = numero_conta.Trim();
                    objConta.saldo_conta = saldo_conta;
                    objConta.id_banco = id_banco;
                    objConta.status_conta = status_conta == null ? false : true;

                    try
                    {
                        if (cod == null)
                        {
                            objdao.SalvarConta(objConta);
                        }
                        else
                        {
                            objConta.id_conta = Convert.ToInt32(cod);
                            objdao.AlterarConta(objConta);
                        }
                        ViewBag.Validar = 1;
                    }
                    catch
                    {

                        ViewBag.Validar = -1;
                    }
                }



                if (cod == null)
                {
                    MontarTitulo(1);
                    pagina = "Nova";
                }
                else
                {
                    MontarTitulo(2);
                    pagina = "Alterar";
                }
                CarregarBanco();
            }
            return View(pagina);

        }
    }
}

Financeiro/FinanceiroWeb/Views/Conta/Alterar.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}

@using (Html.BeginForm("Gravar", "Conta", FormMethod.Post))
{
    <input type="hidden" name="cod" value="@ViewBag.cod" />
    <div class="form-group">
        <label>Selecione o banco:</label>
        <select class="form-control" id="banco_conta" name="id_banco">
          
            @foreach (var item in ViewBag.listaBancos)
            {
                <option value="@item.id_banco" @{
                    string marcar = "";
                    if (item.id_banco == ViewBag.banco)
                    {
                        marcar = "selected";
                    }

                }@marcar >@item.nome_banco</option>
                    }

        </select>
        <label>Agência</label>
        <input class="form-control" placeholder="Digite aqui.." id="agencia_conta" name="agencia_conta" value="@ViewBag.agencia" />
        <label id="val_ag_conta" class="estilo-validar"></label>
        <br />
        <label>Número conta</label>
        <input class="form-control" placeholder="Digite aqui.." id="numero_conta" name="numero_conta" value="@ViewBag.numero" />
        <label id="val_num_conta" class="estilo-validar"></label>
        <br />
        <label>Saldo</label>
        <input class="form-control" placeholder="Digite aqui.." id="saldo_conta" name="saldo_conta" value="@ViewBag.saldo" />
        <label id="val_saldo_conta" class="estilo-validar"></label>
        <br />

        <div class="checkbox">
            <label>
                <input type="checkbox" name="status_conta" @{
                    string check = "";
                    if (@ViewBag.status == "Ativo")
                    {
                        check = "checked";
                    }
                } @check />Ativo
            </label>
        </div>
        <br />
    </div>
    <button type="submit" class="btn btn-success" name="btn" onclick="return ValidarCampos(4)">Salvar</button>
    <button type="submit" class="btn btn-danger" name="btn" value="excluir">Excluir</button>
}


Financeiro/FinanceiroWeb/Views/Conta/Consultar.cshtml

@{

    Layout = "~/Views/Shared/_template.cshtml";
}

<div class="row">
    <div class="col-md-12">
        
        <h2>CONSULTAR CONTA</h2>
        <h5>Aqui você consulta suas contas!</h5>

    </div>
</div>
<!-- /. ROW  -->
<hr />
<div class="row">
    <div class="col-md-12">
        <!-- Advanced Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Lista de Contas
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Banco</th>
                                <th>Agência </th>
                                <th>Número </th>
                                <th>Saldo </th>
                                <th>Status </th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in ViewBag.listarContas)
                            {
                                string sit = "";

                                if (item.Status)
                                {
                                    sit = "Ativo";
                                }
                                else
                                {
                                    sit = "Inativo";
                                }
                            <tr class="odd gradeX">
                                <td> @item.Banco</td>
                                <td> @item.Agencia</td>
                                <td> @item.Numero</td>
                                <td> @item.Saldo</td>
                                <td> @sit</td>
                                <td>
                                    <a href="/Conta/Alterar?cod=@item.Conta&banco=@item.CodBanco&agencia=@item.Agencia&numero=@item.Numero&saldo=@item.Saldo&status=@sit" class="btn btn-warning btn-xs">Alterar</a>
                                </td>
                            </tr>
                            }

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!--End Advanced Tables -->
    </div>
</div>


Financeiro/FinanceiroWeb/Views/Conta/Nova.cshtml

@{
    Layout = "~/Views/Shared/_template.cshtml";
}

@using (Html.BeginForm("Gravar", "Conta", FormMethod.Post))
{
    <div class="form-group">
        <label>Selecione o banco:</label>
        <select class="form-control" id="banco_conta" name="id_banco">
            <option value="" selected>Selecione</option>
            @foreach (var item in ViewBag.listaBancos)
            {
                <option value="@item.id_banco">@item.nome_banco</option>
            }
            </select>
        <label id="val_ban_conta" class="estilo-validar"></label>
    </div>
    <div class="form-group">
        <label>Agência</label>
        <input class="form-control" placeholder="Digite aqui.." id="agencia_conta" name="agencia_conta" />
        <label id="val_ag_conta" class="estilo-validar"></label>
    </div>
    <div class="form-group">
        <label>Número conta</label>
        <input class="form-control" placeholder="Digite aqui.." id="numero_conta" name="numero_conta" />
        <label id="val_num_conta" class="estilo-validar"></label>
    </div>
    <div class="form-group">
        <label>Saldo</label>
        <input class="form-control" placeholder="Digite aqui.." id="saldo_conta" name="saldo_conta" />
        <label id="val_saldo_conta" class="estilo-validar"></label>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="status_conta" value="1" />Ativo
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-success" name="btnSalvar" onclick="return ValidarCampos(4)">Salvar</button>
}
